package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.data.models;

// Generated Nov 19, 2014 7:40:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private Integer id;
	private User user;
	private Set<SimulationConfiguration> simulationConfigurations = new HashSet<SimulationConfiguration>(0);

	public Project() {
	}

	public Project(User user) {
		this.user = user;
	}

	public Project(User user, Set<SimulationConfiguration> simulationConfigurations) {
		this.user = user;
		this.simulationConfigurations = simulationConfigurations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Set<SimulationConfiguration> getSimulationConfigurations() {
		return this.simulationConfigurations;
	}

	public void setSimulationConfigurations(Set<SimulationConfiguration> simulationConfigurations) {
		this.simulationConfigurations = simulationConfigurations;
	}

}
