package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.data.models;

// Generated Nov 5, 2014 11:26:09 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SimulationConfiguration generated by hbm2java
 */
public class SimulationConfiguration implements java.io.Serializable {

	private Integer id;
	private SimulationData simulationData;
	private Set<UserSimulationConfiguration> userSimulationConfigurations = new HashSet<UserSimulationConfiguration>(
			0);
	private Set<SimulationExecution> simulationExecutions = new HashSet<SimulationExecution>(
			0);

	public SimulationConfiguration() {
	}

	public SimulationConfiguration(SimulationData simulationData,
			Set<UserSimulationConfiguration> userSimulationConfigurations,
			Set<SimulationExecution> simulationExecutions) {
		this.simulationData = simulationData;
		this.userSimulationConfigurations = userSimulationConfigurations;
		this.simulationExecutions = simulationExecutions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SimulationData getSimulationData() {
		return this.simulationData;
	}

	public void setSimulationData(SimulationData simulationData) {
		this.simulationData = simulationData;
	}

	public Set<UserSimulationConfiguration> getUserSimulationConfigurations() {
		return this.userSimulationConfigurations;
	}

	public void setUserSimulationConfigurations(
			Set<UserSimulationConfiguration> userSimulationConfigurations) {
		this.userSimulationConfigurations = userSimulationConfigurations;
	}

	public Set<SimulationExecution> getSimulationExecutions() {
		return this.simulationExecutions;
	}

	public void setSimulationExecutions(
			Set<SimulationExecution> simulationExecutions) {
		this.simulationExecutions = simulationExecutions;
	}

}
