package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.data.models;

// Generated Nov 19, 2014 7:40:52 PM by Hibernate Tools 4.0.0

/**
 * SimulationRun generated by hbm2java
 */
public class SimulationRun implements java.io.Serializable {

	private Integer id;
	private SimulationExecution simulationExecution;

	public SimulationRun() {
	}

	public SimulationRun(SimulationExecution simulationExecution) {
		this.simulationExecution = simulationExecution;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SimulationExecution getSimulationExecution() {
		return this.simulationExecution;
	}

	public void setSimulationExecution(SimulationExecution simulationExecution) {
		this.simulationExecution = simulationExecution;
	}

}
