package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.data.models;

// Generated Nov 19, 2014 7:40:52 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SimulationConfiguration generated by hbm2java
 */
public class SimulationConfiguration implements java.io.Serializable {

	private Integer id;
	private User user;
	private Project project;
	private SimulationData simulationData;
	private Set<SimulationExecution> simulationExecutions = new HashSet<SimulationExecution>(0);

	public SimulationConfiguration() {
	}

	public SimulationConfiguration(User user, Project project) {
		this.user = user;
		this.project = project;
	}

	public SimulationConfiguration(User user, Project project, SimulationData simulationData,
			Set<SimulationExecution> simulationExecutions) {
		this.user = user;
		this.project = project;
		this.simulationData = simulationData;
		this.simulationExecutions = simulationExecutions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public SimulationData getSimulationData() {
		return this.simulationData;
	}

	public void setSimulationData(SimulationData simulationData) {
		this.simulationData = simulationData;
	}

	public Set<SimulationExecution> getSimulationExecutions() {
		return this.simulationExecutions;
	}

	public void setSimulationExecutions(Set<SimulationExecution> simulationExecutions) {
		this.simulationExecutions = simulationExecutions;
	}

}
