package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.data.models;

// Generated Oct 20, 2014 11:17:46 PM by Hibernate Tools 4.0.0

/**
 * SimulationRun generated by hbm2java
 */
public class SimulationRun implements java.io.Serializable {

	private Integer id;
	private SimulationConfiguration simulationConfiguration;

	public SimulationRun() {
	}

	public SimulationRun(SimulationConfiguration simulationConfiguration) {
		this.simulationConfiguration = simulationConfiguration;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SimulationConfiguration getSimulationConfiguration() {
		return this.simulationConfiguration;
	}

	public void setSimulationConfiguration(
			SimulationConfiguration simulationConfiguration) {
		this.simulationConfiguration = simulationConfiguration;
	}

}
