package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.data.models;

// Generated Oct 16, 2014 10:41:33 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SimulationConfiguration generated by hbm2java
 */
public class SimulationConfiguration implements java.io.Serializable {

	private Integer id;
	private Set simulationRuns = new HashSet(0);

	public SimulationConfiguration() {
	}

	public SimulationConfiguration(Set simulationRuns) {
		this.simulationRuns = simulationRuns;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set getSimulationRuns() {
		return this.simulationRuns;
	}

	public void setSimulationRuns(Set simulationRuns) {
		this.simulationRuns = simulationRuns;
	}

}
