package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.data.models;

// Generated Nov 5, 2014 11:26:09 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String email;
	private String password;
	private Date registrationDate;
	private Set<UserSimulationConfiguration> userSimulationConfigurations = new HashSet<UserSimulationConfiguration>(
			0);

	public User() {
	}

	public User(String email, String password, Date registrationDate) {
		this.email = email;
		this.password = password;
		this.registrationDate = registrationDate;
	}

	public User(String email, String password, Date registrationDate,
			Set<UserSimulationConfiguration> userSimulationConfigurations) {
		this.email = email;
		this.password = password;
		this.registrationDate = registrationDate;
		this.userSimulationConfigurations = userSimulationConfigurations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	public Set<UserSimulationConfiguration> getUserSimulationConfigurations() {
		return this.userSimulationConfigurations;
	}

	public void setUserSimulationConfigurations(
			Set<UserSimulationConfiguration> userSimulationConfigurations) {
		this.userSimulationConfigurations = userSimulationConfigurations;
	}

}
