package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.data.models;

// Generated Nov 10, 2014 7:52:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String email;
	private String password;
	private int role;
	private Date registrationDate;
	private Date lastActivityDate;
	private int activationState;
	private Set<UserInfo> userInfos = new HashSet<UserInfo>(0);
	private Set<AuthenticationToken> authenticationTokens = new HashSet<AuthenticationToken>(0);
	private Set<UserSimulationConfiguration> userSimulationConfigurations = new HashSet<UserSimulationConfiguration>(0);

	public User() {
	}

	public User(String email, String password, int role, Date registrationDate, int activationState) {
		this.email = email;
		this.password = password;
		this.role = role;
		this.registrationDate = registrationDate;
		this.activationState = activationState;
	}

	public User(String email, String password, int role, Date registrationDate, Date lastActivityDate,
			int activationState, Set<UserInfo> userInfos, Set<AuthenticationToken> authenticationTokens,
			Set<UserSimulationConfiguration> userSimulationConfigurations) {
		this.email = email;
		this.password = password;
		this.role = role;
		this.registrationDate = registrationDate;
		this.lastActivityDate = lastActivityDate;
		this.activationState = activationState;
		this.userInfos = userInfos;
		this.authenticationTokens = authenticationTokens;
		this.userSimulationConfigurations = userSimulationConfigurations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getRole() {
		return this.role;
	}

	public void setRole(int role) {
		this.role = role;
	}

	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	public Date getLastActivityDate() {
		return this.lastActivityDate;
	}

	public void setLastActivityDate(Date lastActivityDate) {
		this.lastActivityDate = lastActivityDate;
	}

	public int getActivationState() {
		return this.activationState;
	}

	public void setActivationState(int activationState) {
		this.activationState = activationState;
	}

	public Set<UserInfo> getUserInfos() {
		return this.userInfos;
	}

	public void setUserInfos(Set<UserInfo> userInfos) {
		this.userInfos = userInfos;
	}

	public Set<AuthenticationToken> getAuthenticationTokens() {
		return this.authenticationTokens;
	}

	public void setAuthenticationTokens(Set<AuthenticationToken> authenticationTokens) {
		this.authenticationTokens = authenticationTokens;
	}

	public Set<UserSimulationConfiguration> getUserSimulationConfigurations() {
		return this.userSimulationConfigurations;
	}

	public void setUserSimulationConfigurations(Set<UserSimulationConfiguration> userSimulationConfigurations) {
		this.userSimulationConfigurations = userSimulationConfigurations;
	}

}
