package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.data.models;

// Generated Nov 7, 2014 10:24:01 PM by Hibernate Tools 4.0.0

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private Integer id;
	private User user;
	private String name;
	private String value;

	public UserInfo() {
	}

	public UserInfo(User user, String name) {
		this.user = user;
		this.name = name;
	}

	public UserInfo(User user, String name, String value) {
		this.user = user;
		this.name = name;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
