package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.data.models;

// Generated Nov 7, 2014 10:24:01 PM by Hibernate Tools 4.0.0

/**
 * UserSimulationConfiguration generated by hbm2java
 */
public class UserSimulationConfiguration implements java.io.Serializable {

	private UserSimulationConfigurationId id;
	private SimulationConfiguration simulationConfiguration;
	private User user;

	public UserSimulationConfiguration() {
	}

	public UserSimulationConfiguration(UserSimulationConfigurationId id,
			SimulationConfiguration simulationConfiguration, User user) {
		this.id = id;
		this.simulationConfiguration = simulationConfiguration;
		this.user = user;
	}

	public UserSimulationConfigurationId getId() {
		return this.id;
	}

	public void setId(UserSimulationConfigurationId id) {
		this.id = id;
	}

	public SimulationConfiguration getSimulationConfiguration() {
		return this.simulationConfiguration;
	}

	public void setSimulationConfiguration(
			SimulationConfiguration simulationConfiguration) {
		this.simulationConfiguration = simulationConfiguration;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
