package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.data.models;

// Generated Nov 10, 2014 7:52:52 PM by Hibernate Tools 4.0.0

/**
 * UserSimulationConfigurationId generated by hbm2java
 */
public class UserSimulationConfigurationId implements java.io.Serializable {

	private int userId;
	private int configurationId;

	public UserSimulationConfigurationId() {
	}

	public UserSimulationConfigurationId(int userId, int configurationId) {
		this.userId = userId;
		this.configurationId = configurationId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getConfigurationId() {
		return this.configurationId;
	}

	public void setConfigurationId(int configurationId) {
		this.configurationId = configurationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserSimulationConfigurationId))
			return false;
		UserSimulationConfigurationId castOther = (UserSimulationConfigurationId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getConfigurationId() == castOther.getConfigurationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getConfigurationId();
		return result;
	}

}
