package cz.cuni.mff.d3s.jdeeco.cloudsimulator.data.models;

import cz.cuni.mff.d3s.jdeeco.cloudsimulator.common.data.StatisticsSaveMode;

/**
 * SimulationRunStatisticAggdata generated by hbm2java
 */
public class SimulationRunStatisticAggdata implements java.io.Serializable {

	private static final long serialVersionUID = 3308429693967294290L;

	private SimulationRunStatisticAggdataId id;
	private SimulationRunStatistic simulationRunStatistic;
	private byte[] data;

	public SimulationRunStatisticAggdata() {
	}

	public SimulationRunStatisticAggdata(SimulationRunStatistic simulationRunStatistic, StatisticsSaveMode saveType, byte[] data) {
		this.id = new SimulationRunStatisticAggdataId(simulationRunStatistic.getId(), saveType);
		this.simulationRunStatistic = simulationRunStatistic;
		this.data = data;
	}

	public SimulationRunStatisticAggdataId getId() {
		return this.id;
	}

	public void setId(SimulationRunStatisticAggdataId id) {
		this.id = id;
	}

	public SimulationRunStatistic getSimulationRunStatistic() {
		return this.simulationRunStatistic;
	}

	public void setSimulationRunStatistic(SimulationRunStatistic simulationRunStatistic) {
		this.simulationRunStatistic = simulationRunStatistic;
	}

	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

}
