package cz.cuni.mff.d3s.jdeeco.cloudsimulator.data.models;

/**
 * SimulationRunVariable generated by hbm2java
 */
public class SimulationRunVariable implements java.io.Serializable {

	private static final long serialVersionUID = -2570737987551220880L;

	private SimulationRunVariableId id;
	private SimulationExecutionVariable simulationExecutionVariable;
	private SimulationRun simulationRun;
	private byte[] data;

	public SimulationRunVariable() {
	}

	public SimulationRunVariable(SimulationRunVariableId id, SimulationExecutionVariable simulationExecutionVariable,
			SimulationRun simulationRun, byte[] data) {
		this.id = id;
		this.simulationExecutionVariable = simulationExecutionVariable;
		this.simulationRun = simulationRun;
		this.data = data;
	}

	public SimulationRunVariableId getId() {
		return this.id;
	}

	public void setId(SimulationRunVariableId id) {
		this.id = id;
	}

	public SimulationExecutionVariable getSimulationExecutionVariable() {
		return this.simulationExecutionVariable;
	}

	public void setSimulationExecutionVariable(SimulationExecutionVariable simulationExecutionVariable) {
		this.simulationExecutionVariable = simulationExecutionVariable;
	}

	public SimulationRun getSimulationRun() {
		return this.simulationRun;
	}

	public void setSimulationRun(SimulationRun simulationRun) {
		this.simulationRun = simulationRun;
	}

	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}
}
