package cz.cuni.mff.d3s.jdeeco.cloudsimulator.data.models;

/**
 * SimulationRunVariableId generated by hbm2java
 */
public class SimulationRunVariableId implements java.io.Serializable {

	private static final long serialVersionUID = -492578260702191284L;

	private int runId;
	private int executionVariableId;

	public SimulationRunVariableId() {
	}

	public SimulationRunVariableId(int runId, int executionVariableId) {
		this.runId = runId;
		this.executionVariableId = executionVariableId;
	}

	public int getRunId() {
		return this.runId;
	}

	public void setRunId(int runId) {
		this.runId = runId;
	}

	public int getExecutionVariableId() {
		return this.executionVariableId;
	}

	public void setExecutionVariableId(int executionVariableId) {
		this.executionVariableId = executionVariableId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SimulationRunVariableId))
			return false;
		SimulationRunVariableId castOther = (SimulationRunVariableId) other;

		return (this.getRunId() == castOther.getRunId())
				&& (this.getExecutionVariableId() == castOther.getExecutionVariableId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRunId();
		result = 37 * result + this.getExecutionVariableId();
		return result;
	}
}
