package cz.cuni.mff.d3s.jdeeco.cloudsimulator.data.models;

import java.util.HashSet;
import java.util.Set;

/**
 * SimulationRunStatistic generated by hbm2java
 */
public class SimulationRunStatistic implements java.io.Serializable {

	private static final long serialVersionUID = 7504427165021227108L;

	private Long id;
	private SimulationExecutionStatistic simulationExecutionStatistic;
	private SimulationRun simulationRun;
	private byte[] vectorData;
	private Set<SimulationRunStatisticAggdata> simulationRunStatisticAggdatas = new HashSet<SimulationRunStatisticAggdata>(
			0);

	public SimulationRunStatistic() {
	}

	public SimulationRunStatistic(SimulationExecutionStatistic simulationExecutionStatistic,
			SimulationRun simulationRun) {
		this.simulationExecutionStatistic = simulationExecutionStatistic;
		this.simulationRun = simulationRun;
	}

	public SimulationRunStatistic(SimulationExecutionStatistic simulationExecutionStatistic,
			SimulationRun simulationRun, byte[] vectorData,
			Set<SimulationRunStatisticAggdata> simulationRunStatisticAggdatas) {
		this.simulationExecutionStatistic = simulationExecutionStatistic;
		this.simulationRun = simulationRun;
		this.vectorData = vectorData;
		this.simulationRunStatisticAggdatas = simulationRunStatisticAggdatas;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public SimulationExecutionStatistic getSimulationExecutionStatistic() {
		return this.simulationExecutionStatistic;
	}

	public void setSimulationExecutionStatistic(SimulationExecutionStatistic simulationExecutionStatistic) {
		this.simulationExecutionStatistic = simulationExecutionStatistic;
	}

	public SimulationRun getSimulationRun() {
		return this.simulationRun;
	}

	public void setSimulationRun(SimulationRun simulationRun) {
		this.simulationRun = simulationRun;
	}

	public byte[] getVectorData() {
		return this.vectorData;
	}

	public void setVectorData(byte[] vectorData) {
		this.vectorData = vectorData;
	}

	public Set<SimulationRunStatisticAggdata> getSimulationRunStatisticAggdatas() {
		return this.simulationRunStatisticAggdatas;
	}

	public void setSimulationRunStatisticAggdatas(Set<SimulationRunStatisticAggdata> simulationRunStatisticAggdatas) {
		this.simulationRunStatisticAggdatas = simulationRunStatisticAggdatas;
	}
}
