ALTER TABLE `simulation_data`
ADD COLUMN `Description` VARCHAR(1000) NOT NULL DEFAULT '',
ADD COLUMN `Created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN `VCSType` INT(4) NOT NULL,
ADD COLUMN `RepositoryURL` VARCHAR(2000) NOT NULL,
ADD COLUMN `PathToPom` VARCHAR(256) NOT NULL,
ADD COLUMN `MavenGoals` VARCHAR(1000) NOT NULL;