
package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimulatorServiceImplService", targetNamespace = "http://service.jobmanager.cloudsimulator.jdeeco.d3s.mff.cuni.cz/", wsdlLocation = "http://localhost:9999/ws/simulator?wsdl")
public class SimulatorServiceImplService
    extends Service
{

    private final static URL SIMULATORSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMULATORSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SIMULATORSERVICEIMPLSERVICE_QNAME = new QName("http://service.jobmanager.cloudsimulator.jdeeco.d3s.mff.cuni.cz/", "SimulatorServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/simulator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMULATORSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SIMULATORSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SimulatorServiceImplService() {
        super(__getWsdlLocation(), SIMULATORSERVICEIMPLSERVICE_QNAME);
    }

    public SimulatorServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMULATORSERVICEIMPLSERVICE_QNAME, features);
    }

    public SimulatorServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SIMULATORSERVICEIMPLSERVICE_QNAME);
    }

    public SimulatorServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMULATORSERVICEIMPLSERVICE_QNAME, features);
    }

    public SimulatorServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimulatorServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimulatorService
     */
    @WebEndpoint(name = "SimulatorServiceImplPort")
    public SimulatorService getSimulatorServiceImplPort() {
        return super.getPort(new QName("http://service.jobmanager.cloudsimulator.jdeeco.d3s.mff.cuni.cz/", "SimulatorServiceImplPort"), SimulatorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimulatorService
     */
    @WebEndpoint(name = "SimulatorServiceImplPort")
    public SimulatorService getSimulatorServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.jobmanager.cloudsimulator.jdeeco.d3s.mff.cuni.cz/", "SimulatorServiceImplPort"), SimulatorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMULATORSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SIMULATORSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SIMULATORSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
