
package cz.cuni.mff.d3s.jdeeco.cloudsimulator.jobmanager.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimulatorService", targetNamespace = "http://service.jobmanager.cloudsimulator.jdeeco.d3s.mff.cuni.cz/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SimulatorService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateSimulation")
    @WebResult(partName = "return")
    @Action(input = "http://service.jobmanager.cloudsimulator.jdeeco.d3s.mff.cuni.cz/SimulatorService/CreateSimulationRequest", output = "http://service.jobmanager.cloudsimulator.jdeeco.d3s.mff.cuni.cz/SimulatorService/CreateSimulationResponse")
    public String createSimulation();

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "GetStatus")
    @Action(input = "http://service.jobmanager.cloudsimulator.jdeeco.d3s.mff.cuni.cz/SimulatorService/GetStatusRequest", output = "http://service.jobmanager.cloudsimulator.jdeeco.d3s.mff.cuni.cz/SimulatorService/GetStatusResponse")
    public void getStatus(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "StartSimulation")
    @Action(input = "http://service.jobmanager.cloudsimulator.jdeeco.d3s.mff.cuni.cz/SimulatorService/StartSimulationRequest", output = "http://service.jobmanager.cloudsimulator.jdeeco.d3s.mff.cuni.cz/SimulatorService/StartSimulationResponse")
    public void startSimulation(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
